services:
  jellyfish-classifier:
    image: jellyfish-classifier:latest
    container_name: tensorflow_jupyter_uv

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=2
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PYTHONPATH=/app/src:/app

    volumes:
      - .:/app
      - uv-cache:/root/.cache/uv

    ports:
      - "8888:8888"

    working_dir: /app

    command: >
      uv run jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root

    restart: unless-stopped

volumes:
  uv-cache:
