dataset:
  img_size: 224
  batch_size: 16
  seed: 42

model:
  num_classes: 5
  input_shape: [224, 224, 3]
  dropout_rate: 0.3
  fine_tune_layers: 30
  optimizer: "adam"
  learning_rate: 0.001

training:
  epochs: 100
  early_stopping_patience: 8
  checkpoint_monitor: "val_accuracy"
  checkpoint_mode: "max"
  save_best_only: true
  verbose: 1
  output_dir: "outputs"

download:
  max_images_per_species: 1000
  per_page: 50
  api_sleep_time: 2
  image_size: "medium"
  species:
    - name: "Aurelia aurita"
      preferred_common_name: "Common Moon Jelly"
      taxon_id: 48328
    - name: "Pelagia noctiluca"
      preferred_common_name: "Mauve Stinger"
      taxon_id: 256089
    - name: "Chrysaora hysoscella"
      preferred_common_name: "Compass Jelly"
      taxon_id: 360314
    - name: "Cotylorhiza tuberculata"
      preferred_common_name: "Fried Egg Jelly"
      taxon_id: 324852
    - name: "Rhizostoma pulmo"
      preferred_common_name: "Barrel Jelly"
      taxon_id: 319371